apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: msxot9vqx-python 
  janus-idp.io/tekton: msxot9vqx-python
  backstage.io/kubernetes-id: msxot9vqx-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: msxot9vqx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml