apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: msxot9vqx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: msxot9vqx-python 
  name: msxot9vqx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: msxot9vqx-python 
